# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Paso 1: Instalar Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.20.6'
    displayName: 'Install Node.js'

  # Paso 2: Instalar dependencias y construir la aplicación Angular
  - script: |
      npm install -g @angular/cli
      npm install
      ng build --configuration=production
    displayName: 'Build Angular App'

 # Paso 3: Crear un archivo .zip con los artefactos de la construcción
 # - script: |
#      cd dist
 #     zip -r angular-app.zip *
 #   displayName: 'Create .zip Archive'

  # Paso 4: Publicar artefactos
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'  # Ruta al archivo .zip
      ArtifactName: 'dist'
    displayName: 'Publish Build Artifacts'